// This file is auto-generated by @hey-api/openapi-ts

export const $ReadingTimeResponse = {
    required: ['readingTime'],
    type: 'object',
    properties: {
        readingTime: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;