// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoReadingtimeApiData, GetUmbracoReadingtimeApiResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.contentKey
 * @param data.dataTypeKey
 * @param data.culture
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoReadingtimeApi = (data: GetUmbracoReadingtimeApiData = {}): CancelablePromise<GetUmbracoReadingtimeApiResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/readingtime/api',
    query: {
        contentKey: data.contentKey,
        dataTypeKey: data.dataTypeKey,
        culture: data.culture
    }
}); };