// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54813' | (string & {});
};

export type ReadingTimeResponse = {
    updateDate: string;
    readingTime: string;
};

export type GetUmbracoReadingTimeApiV1Data = {
    body?: never;
    path?: never;
    query?: {
        contentKey?: string;
        dataTypeKey?: string;
        culture?: string;
    };
    url: '/umbraco/ReadingTime/api/v1';
};

export type GetUmbracoReadingTimeApiV1Responses = {
    /**
     * OK
     */
    200: ReadingTimeResponse;
};

export type GetUmbracoReadingTimeApiV1Response = GetUmbracoReadingTimeApiV1Responses[keyof GetUmbracoReadingTimeApiV1Responses];
