// This file is auto-generated by @hey-api/openapi-ts

export type ReadingTimeResponse = {
    updateDate: string;
    readingTime: string;
};

export type GetUmbracoReadingtimeApiData = {
    contentKey?: string;
    culture?: string;
    dataTypeKey?: string;
};

export type GetUmbracoReadingtimeApiResponse = ((ReadingTimeResponse));