// This file is auto-generated by @hey-api/openapi-ts

export type ReadingTimeResponse = {
    readingTime: string;
};

export type GetUmbracoReadingtimeApiData = {
    contentKey?: string;
    culture?: string;
    dataTypeKey?: string;
};

export type GetUmbracoReadingtimeApiResponse = ReadingTimeResponse;

export type $OpenApiTs = {
    '/umbraco/readingtime/api': {
        get: {
            req: GetUmbracoReadingtimeApiData;
            res: {
                /**
                 * OK
                 */
                200: ReadingTimeResponse;
            };
        };
    };
};