name: Release
on:
  workflow_dispatch:
jobs:
  build:
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-template.yml@main
    with:
      project-name: 'jcdcdev.Umbraco.ReadingTime'
      project-path: './src/jcdcdev.Umbraco.ReadingTime/jcdcdev.Umbraco.ReadingTime.csproj'
  release:
    needs:
      - build
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/release-template.yml@main
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}